# Generated by Django 5.2.17 on 2026-08-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='À propos de Com’Unity', max_length=200, verbose_name='Titre')),
                ('header_image', models.ImageField(upload_to='about/header/', verbose_name="Image d'en-tête")),
                ('main_image', models.ImageField(upload_to='about/main/', verbose_name='Image principale')),
                ('introduction', models.TextField(verbose_name='Présentation')),
                ('mission', models.TextField(verbose_name='Mission')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Page À propos',
                'verbose_name_plural': 'Page À propos',
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='home/hero/', verbose_name='Image')),
                ('button_text', models.CharField(default='Découvrir nos actions', max_length=100, verbose_name='Texte du bouton')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='Lien du bouton')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Slide de l'accueil",
                'verbose_name_plural': "Slides de l'accueil",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('role', models.CharField(choices=[('founder', 'Fondateur'), ('member', 'Membre')], default='member', max_length=20, verbose_name='Rôle')),
                ('position', models.CharField(max_length=200, verbose_name='Poste / Fonction')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='about/team/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['order'],
            },
        ),
    ]
