# Generated by Django 5.2.17 on 2026-08-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('header', 'Image en-tête'), ('main', 'Image principale')], max_length=20, verbose_name="Type d'image")),
                ('image', models.ImageField(upload_to='about/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Image active')),
            ],
            options={
                'verbose_name': 'Image de la page À propos',
                'verbose_name_plural': 'Images de la page À propos',
            },
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Image active')),
            ],
            options={
                'verbose_name': "Image de l'accueil",
                'verbose_name_plural': "Image de l'accueil",
            },
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='HomeHero',
        ),
    ]
