# Generated by Django 5.2.17 on 2026-09-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutimage_homeimage_delete_aboutpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('ecologie', 'Transition écologique'), ('ess', 'Économie sociale et solidaire'), ('citoyennete', 'Éducation citoyenne')], max_length=30, verbose_name='Catégorie')),
                ('short_description', models.CharField(max_length=300, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image du projet')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminé'), ('upcoming', 'À venir')], default='ongoing', max_length=20, verbose_name='Statut')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
