# Generated by Django 5.2.17 on 2026-09-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': "Image d'en-tête des projets",
                'verbose_name_plural': "Image d'en-tête des projets",
            },
        ),
    ]
