# Generated by Django 5.2.17 on 2026-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectheaderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=300, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Image')),
                ('icon', models.CharField(default='fa-leaf', max_length=50, verbose_name='Icône Font Awesome')),
                ('interventions', models.TextField(blank=True, help_text='Séparer les éléments par une virgule.', verbose_name="Domaines d'intervention")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Service actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
