# Generated by Django 5.2.17 on 2026-09-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('category', models.CharField(choices=[('environment', 'Environnement'), ('education', 'Éducation'), ('entrepreneurship', 'Entrepreneuriat'), ('community', 'Communauté'), ('events', 'Événements')], default='community', max_length=30, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo de la galerie',
                'verbose_name_plural': 'Photos de la galerie',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
