# Generated by Django 5.2.17 on 2026-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('domain', models.CharField(choices=[('ecologie', 'Transition écologique'), ('ess', 'Économie sociale et solidaire'), ('citoyennete', 'Éducation citoyenne'), ('communication', 'Communication'), ('autre', 'Autre')], max_length=30, verbose_name='Domaine')),
                ('message', models.TextField(verbose_name='Motivation')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('processing', 'En cours'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='new', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
            ],
            options={
                'verbose_name': 'Candidature bénévole',
                'verbose_name_plural': 'Candidatures bénévoles',
                'ordering': ['-created_at'],
            },
        ),
    ]
