# Generated by Django 5.2.17 on 2026-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_volunteerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='volunteer/', verbose_name="Image de l'en-tête")),
                ('is_active', models.BooleanField(default=True, verbose_name='Image active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image en-tête bénévole',
                'verbose_name_plural': 'Image en-tête bénévole',
            },
        ),
    ]
