# Generated by Django 5.2.17 on 2026-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_volunteerheaderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contact/', verbose_name="Image de l'en-tête")),
                ('is_active', models.BooleanField(default=True, verbose_name='Image active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Image en-tête Contact',
                'verbose_name_plural': 'Image en-tête Contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
