# Generated by Django 5.2.17 on 2026-09-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_donationheaderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('transition', 'Transition écologique'), ('ess', 'Économie sociale et solidaire'), ('education', 'Éducation citoyenne'), ('mobilisation', 'Mobilisation communautaire'), ('accompagnement', 'Accompagnement'), ('reseau', 'Mise en réseau')], max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='actions/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Image de page d'action",
                'verbose_name_plural': "Images des pages d'action",
            },
        ),
    ]
