# Generated by Django 5.2.17 on 2026-09-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_actionpageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('association', "Vie de l'association"), ('environnement', 'Environnement'), ('citoyennete', 'Éducation citoyenne'), ('ess', 'Économie sociale et solidaire'), ('evenement', 'Événement'), ('partenariat', 'Partenariat')], default='association', max_length=30, verbose_name='Catégorie')),
                ('image', models.ImageField(upload_to='actualites/', verbose_name='Image')),
                ('short_description', models.TextField(verbose_name='Résumé')),
                ('content', models.TextField(verbose_name="Contenu de l'article")),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Auteur')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre à la une')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='ActualiteHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='actualites/header/', verbose_name="Image d'en-tête")),
                ('is_active', models.BooleanField(default=True, verbose_name='Image active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Image d'en-tête Actualités",
                'verbose_name_plural': "Image d'en-tête Actualités",
            },
        ),
    ]
