# Generated by Django 5.2.17 on 2026-09-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_actualite_actualiteheaderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='rapports/couvertures/', verbose_name='Image de couverture')),
                ('pdf', models.FileField(upload_to='rapports/pdf/', verbose_name='Document PDF')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rapport annuel',
                'verbose_name_plural': 'Rapports annuels',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='RapportHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rapports/header/', verbose_name="Image d'en-tête")),
                ('is_active', models.BooleanField(default=True, verbose_name='Image active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Image d'en-tête des rapports",
                'verbose_name_plural': "Image d'en-tête des rapports",
            },
        ),
    ]
