# Generated by Django 5.2.17 on 2026-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rapportannuel_rapportheaderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du partenaire')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(upload_to='partenaires/logos/', verbose_name='Logo')),
                ('partnership_type', models.CharField(choices=[('institutionnel', 'Partenaire institutionnel'), ('technique', 'Partenaire technique'), ('financier', 'Partenaire financier'), ('associatif', 'Partenaire associatif'), ('communautaire', 'Partenaire communautaire'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Type de partenariat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Site internet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartenaireHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partenaires/header/', verbose_name="Image d'en-tête")),
                ('is_active', models.BooleanField(default=True, verbose_name='Image active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Image d'en-tête des partenaires",
                'verbose_name_plural': "Image d'en-tête des partenaires",
            },
        ),
    ]
